/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import DAO.FinanceiroDAO;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author ryanp
 */
public class telaRelatorioFinanceiro extends javax.swing.JFrame {

     private FinanceiroDAO financeiroDAO;
    
    public telaRelatorioFinanceiro() {
        initComponents();
        financeiroDAO = new FinanceiroDAO(); 
       
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNFecharRelatorio = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnADDLucro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblLucroMes = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblSaldoFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Relatorio Financeiro");

        BTNFecharRelatorio.setText("Fechar relatorio mensal");
        BTNFecharRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFecharRelatorioActionPerformed(evt);
            }
        });

        btnGastos.setText("Adicionar gastos");
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });

        btnRelatorio.setText(" relatorio mensal");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnADDLucro.setText("Adicionar Lucro");
        btnADDLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDLucroActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblLucroMes.setText("Lucro do mês: ");

        lblGastos.setText("Gastos do mês: ");

        lblSaldoFinal.setText("Saldo final: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNFecharRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnADDLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldoFinal)
                    .addComponent(lblGastos)
                    .addComponent(lblLucroMes))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblLucroMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGastos)
                .addGap(15, 15, 15)
                .addComponent(lblSaldoFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNFecharRelatorio)
                .addGap(44, 44, 44)
                .addComponent(btnGastos)
                .addGap(38, 38, 38)
                .addComponent(btnRelatorio)
                .addGap(40, 40, 40)
                .addComponent(btnADDLucro)
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDLucroActionPerformed
       TelaAdicionarLucro t = new TelaAdicionarLucro(financeiroDAO); 
       t.setVisible(true);
    }//GEN-LAST:event_btnADDLucroActionPerformed

    private void BTNFecharRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFecharRelatorioActionPerformed
        financeiroDAO.virarMes(); 
        atualizarDados();
    }//GEN-LAST:event_BTNFecharRelatorioActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
         TelaAdicionarGasto t = new TelaAdicionarGasto(financeiroDAO);  
         t.setVisible(true);     
    }//GEN-LAST:event_btnGastosActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        financeiroDAO.mostrarMes();
        atualizarDados();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaRelatorioFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaRelatorioFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaRelatorioFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaRelatorioFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaRelatorioFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNFecharRelatorio;
    private javax.swing.JButton btnADDLucro;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblLucroMes;
    private javax.swing.JLabel lblSaldoFinal;
    // End of variables declaration//GEN-END:variables

 private void atualizarDados() {
 try {
        
        Connection conn = financeiroDAO.getConnection();  
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Erro: Não foi possível conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;  
        }

       
        String sql = "SELECT lucro_mes, gastos FROM RelatorioFinanceiro WHERE id = 1";
        PreparedStatement stmt = conn.prepareStatement(sql);
        
      
        ResultSet rs = stmt.executeQuery();
        
       
        if (rs.next()) {
            double lucroMes = rs.getDouble("lucro_mes");
            double gastos = rs.getDouble("gastos");
            double saldoFinal = lucroMes - gastos;
            
            lblLucroMes.setText("Lucro do mês: R$ " + lucroMes);
            lblGastos.setText("Gastos do mês: R$ " + gastos);
            lblSaldoFinal.setText("Saldo final: R$ " + saldoFinal);
        }

       
        rs.close();
        stmt.close();
    } catch (SQLException e) {
        
        JOptionPane.showMessageDialog(this, "Erro ao atualizar dados do banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
       
        JOptionPane.showMessageDialog(this, "Erro desconhecido: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    



 }
}
